apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-portfolio
spec:	 	
  replicas: 3
  selector:
    matchLabels:
      app: my-portfolio
  template:
    metadata:
      labels:
        app: my-portfolio
    spec:
      containers:
      - name: my-portfolio
        image: us-central1-docker.pkg.dev/my-portfolio-471118/my-docker-repo/my-portfolio:latest # replace with your image
        ports:
        - containerPort: 8080
