apiVersion: v1
kind: Service
metadata:
  name: my-portfolio-service
spec:
  type: LoadBalancer
  selector:
    app: my-portfolio
  ports:
    - port: 80          # Cluster-wide entry point
      targetPort: 8080  # Maps to Pod’s containerPort
      nodePort: 30036   # Optional, only valid if type=NodePort


